import 'course.dart';

class CourseData {
  static final Map<String, List<Course>> semesterCourses = {
    "Year 1 Semester 1": [
      Course(code: 'HUM1107', title: 'Critical Thinking and Communication', credits: 3.0, grade: 'A'),
      Course(code: 'HUM1108', title: 'English Language Sessional', credits: 1.5, grade: 'A'),
      Course(code: 'MATH1115', title: 'Mathematics-I', credits: 3.0, grade: 'A'),
      Course(code: 'PHY1115', title: 'Physics', credits: 3.0, grade: 'A'),
      Course(code: 'PHY1116', title: 'Physics Lab', credits: 0.75, grade: 'A'),
      Course(code: 'CHEM1115', title: 'Chemistry', credits: 3.0, grade: 'A'),
      Course(code: 'CSE1101', title: 'Elementary Structured Programming', credits: 3.0, grade: 'A'),
      Course(code: 'CSE1102', title: 'Elementary Structured Programming Lab', credits: 1.5, grade: 'A'),
      Course(code: 'CSE1108', title: 'Introduction to Computer Systems', credits: 1.5, grade: 'A'),
    ],
    "Year 1 Semester 2": [
      Course(code: 'MATH1219', title: 'Mathematics-II', credits: 3.0, grade: 'A'),
      Course(code: 'ME1211', title: 'Basic Mechanical Engineering', credits: 3.0, grade: 'A'),
      Course(code: 'ME1214', title: 'Engineering Drawing', credits: 0.75, grade: 'A'),
      Course(code: 'EEE1241', title: 'Basic Electrical Engineering', credits: 3.0, grade: 'A'),
      Course(code: 'EEE1242', title: 'Basic Electrical Engineering Lab', credits: 1.5, grade: 'A'),
      Course(code: 'CSE1200', title: 'Software Development-I', credits: 1.5, grade: 'A'),
      Course(code: 'CSE1203', title: 'Discrete Mathematics', credits: 3.0, grade: 'A'),
      Course(code: 'CSE1205', title: 'Object Oriented Programming', credits: 3.0, grade: 'A'),
      Course(code: 'CSE1206', title: 'Object Oriented Programming Lab', credits: 1.5, grade: 'A'),
    ],
    "Year 2 Semester 1": [
      Course(code: 'HUM2109', title: 'Society, Ethics and Technology', credits: 3.0, grade: 'A'),
      Course(code: 'MATH2101', title: 'Mathematics-III', credits: 3.0, grade: 'A'),
      Course(code: 'EEE2141', title: 'Electronic Devices and Circuits', credits: 3.0, grade: 'A'),
      Course(code: 'EEE2142', title: 'Electronic Devices and Circuits Lab', credits: 1.5, grade: 'A'),
      Course(code: 'CSE2100', title: 'Software Development-II', credits: 0.75, grade: 'A'),
      Course(code: 'CSE2103', title: 'Data Structures', credits: 3.0, grade: 'A'),
      Course(code: 'CSE2104', title: 'Data Structures Lab', credits: 1.5, grade: 'A'),
      Course(code: 'CSE2105', title: 'Digital Logic Design', credits: 3.0, grade: 'A'),
      Course(code: 'CSE2106', title: 'Digital Logic Design Lab', credits: 1.5, grade: 'A'),
    ],
    "Year 2 Semester 2": [
      Course(code: 'MATH2203', title: 'Mathematics-IV', credits: 3.0, grade: 'A'),
      Course(code: 'CSE2200', title: 'Software Development-III', credits: 0.75, grade: 'A'),
      Course(code: 'CSE2201', title: 'Numerical Methods', credits: 3.0, grade: 'A'),
      Course(code: 'CSE2202', title: 'Numerical Methods Lab', credits: 0.75, grade: 'A'),
      Course(code: 'CSE2207', title: 'Algorithms', credits: 3.0, grade: 'A'),
      Course(code: 'CSE2208', title: 'Algorithms Lab', credits: 1.5, grade: 'A'),
      Course(code: 'CSE2211', title: 'Data Communication', credits: 3.0, grade: 'A'),
      Course(code: 'CSE2213', title: 'Computer Architecture', credits: 3.0, grade: 'A'),
      Course(code: 'CSE2214', title: 'Assembly Language Programming', credits: 1.5, grade: 'A'),
    ],
    "Year 3 Semester 1": [
      Course(code: 'HUM3115', title: 'Economics and Accounting', credits: 3.0, grade: 'A'),
      Course(code: 'CSE3100', title: 'Software Development-IV', credits: 0.75, grade: 'A'),
      Course(code: 'CSE3101', title: 'Mathematical Analysis for Computer Science', credits: 3.0, grade: 'A'),
      Course(code: 'CSE3103', title: 'Database', credits: 3.0, grade: 'A'),
      Course(code: 'CSE3104', title: 'Database Lab', credits: 1.5, grade: 'A'),
      Course(code: 'CSE3109', title: 'Digital System Design', credits: 3.0, grade: 'A'),
      Course(code: 'CSE3110', title: 'Digital System Design Lab', credits: 0.75, grade: 'A'),
      Course(code: 'CSE3117', title: 'Microprocessors and Microcontrollers', credits: 3.0, grade: 'A'),
      Course(code: 'CSE3118', title: 'Microprocessors and Microcontrollers Lab', credits: 0.75, grade: 'A'),
    ],
    "Year 3 Semester 2": [
      Course(code: 'HUM3207', title: 'Industrial Law and Safety Management', credits: 3.0, grade: 'A'),
      Course(code: 'CSE3200', title: 'Software Development-V', credits: 0.75, grade: 'A'),
      Course(code: 'CSE3201', title: 'Introduction to Computer Networks', credits: 3.0, grade: 'A'),
      Course(code: 'CSE3202', title: 'Introduction to Computer Networks Lab', credits: 0.75, grade: 'A'),
      Course(code: 'CSE3207', title: 'Introduction to Artificial Intelligence', credits: 3.0, grade: 'A'),
      Course(code: 'CSE3208', title: 'Introduction to Artificial Intelligence Lab', credits: 0.75, grade: 'A'),
      Course(code: 'CSE3213', title: 'Operating System', credits: 3.0, grade: 'A'),
      Course(code: 'CSE3214', title: 'Operating System Lab', credits: 0.75, grade: 'A'),
      Course(code: 'CSE3223', title: 'Information System Design and Software Engineering', credits: 3.0, grade: 'A'),
      Course(code: 'CSE3224', title: 'Information System Design and Software Engineering Lab', credits: 0.75, grade: 'A'),
    ],
    "Year 4 Semester 1": [
      Course(code: 'IPE4111', title: 'Industrial Management', credits: 3.0, grade: 'A'),
      Course(code: 'CSE4100', title: 'Project and Thesis-I', credits: 3.0, grade: 'A'),
      Course(code: 'CSE4113', title: 'Pattern Recognition and Machine Learning', credits: 3.0, grade: 'A'),
      Course(code: 'CSE4114', title: 'Pattern Recognition and Machine Learning Lab', credits: 0.75, grade: 'A'),
      Course(code: 'CSE4129', title: 'Formal Languages and Compilers', credits: 3.0, grade: 'A'),
      Course(code: 'CSE4130', title: 'Formal Languages and Compilers Lab', credits: 0.75, grade: 'A'),
      Course(code: 'CSE....', title: 'Option-I', credits: 3.0, grade: 'A'),
      Course(code: 'CSE....', title: 'Option-I Lab', credits: 0.75, grade: 'A'),
      Course(code: 'CSE....', title: 'Option-II', credits: 3.0, grade: 'A'),
      Course(code: 'CSE....', title: 'Option-II Lab', credits: 0.75, grade: 'A'),
    ],
    "Year 4 Semester 2": [
      Course(code: 'CSE4203', title: 'Computer Graphics', credits: 3.0, grade: 'A'),
      Course(code: 'CSE4204', title: 'Computer Graphics Lab', credits: 0.75, grade: 'A'),
      Course(code: 'CSE4250', title: 'Project and Thesis-II', credits: 3.0, grade: 'A'),
      Course(code: 'CSE....', title: 'Option-III', credits: 3.0, grade: 'A'),
      Course(code: 'CSE....', title: 'Option-III Lab', credits: 0.75, grade: 'A'),
      Course(code: 'CSE....', title: 'Option-IV', credits: 3.0, grade: 'A'),
      Course(code: 'CSE....', title: 'Option-IV Lab', credits: 0.75, grade: 'A'),
      Course(code: 'CSE....', title: 'Option-V', credits: 3.0, grade: 'A'),
    ],
  };
}
